### ISSUE TITLE
Initial Project Setup

### ISSUE THREAD

**Issue by the-duolearn** [DuolearnHQ/Meet#2]
The purpose of this issue is to set up the initial project environment. This includes setting up the project structure, installing dependencies, configuring the development environment, and creating basic templates.

Tasks:
- Create a project structure that follows the best practices and suits the project requirements.
- Install and configure the required dependencies such as node.js, npm, and any project-specific libraries.
- Create a development environment setup, including tools like editor configurations, git hooks, and build scripts.
- Create a basic template for the project that includes starter code, readme files, and license files.
- Ensure that the project structure, dependencies, and development environment are well documented in the project's readme file.

Expected Outcome:
The initial project environment should be set up and ready for development. The project should be easy to understand and accessible for new developers who join the project later. The documentation should be comprehensive and easy to follow, so that any developer can start working on the project without any issues.

**Comment by pavan38kp** [comment]
Hey I would like to take this up

**Comment by RwandaGloria** [comment]
Has this task been assigned already?

**Comment by devnm21** [comment]
Update: This issue will now concentrate on setting up the client alone.
Our current focus will also be on the FE for now.
When the time comes for server requirements, we'll set it up
