### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by devnm21** [DuolearnHQ/Meet#3]
This issue is to discuss the potential features in detail to have for the v1 of the Meet.

**Comment by RwandaGloria** [comment]
Can we talk about it more? Is this a role to be assigned? I'm interested

**Comment by the-duolearn** [comment]
This issue is to simply discuss the features you think should be included in the project. Feel free to jot down what’s on your mind. On 02-May-2023, at 3:25 PM, Gloria Solomon ***@***.***> wrote:﻿
Can we talk about it more? Is this a role to be assigned? I'm interested
