### ISSUE TITLE
Setup Chakra UI with default theme

### ISSUE THREAD

**Issue by pavankpdev** [DuolearnHQ/Meet#7]
We need to set up Chakra UI and set the default color mode as light theme. 

Acceptance Criteria
1. Install and set up Chakra UI in the project
2. Setup Chakra UI for `pages` directory, not for the new `appDir` from NextJS
3. Configure the Chakra UI with default theme
4. Test the Chakra UI components and make sure they are styled correctly.

Reference/Docs 
https://chakra-ui.com/getting-started/nextjs-guide

**Comment by devnm21** [comment]
Note: ChakraUI is already installed and tested to be working. 
Whoever is taking up, may proceed with just setting up a default theme
